language: node_js
node_js:
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
